---
when:
    - event: [push, manual]

steps:
    - name: install
      image: node:24.15.0
      commands:
          - npm clean-install

    - name: validate
      image: node:24.15.0
      commands:
          - npx just validate
