---
when:
    - event: [push, manual]

labels:
    platform: linux/amd64

steps:
    - name: install
      image: node:26.3.0
      commands:
          - npm clean-install

    - name: test
      image: node:26.3.0
      commands:
          - npx just test
          - npx just lint
